#facility.catchments=302618
#facility.facilityId=10019841
#facility.apiToken=xyz
#facility.clientId=12345
#facility.email=email@gmail.com
#facility.password=password

facility.catchments=305682
facility.facilityId=10000312
facility.apiToken=df5c169e104807060c3c049110212a58486713e55a0bdd3576812ab6da61a406
facility.clientId=187077
facility.email=singair2@uhfpo.dghs.gov.bd
facility.password=Sing@1R!*$