#facility.catchments=302618
#facility.facilityId=10019841
#facility.apiToken=xyz
#facility.clientId=12345
#facility.email=email@gmail.com
#facility.password=password


facility.catchments=3056828708
facility.facilityId=10000312
facility.apiToken=30ce5043a533d785fa394227d7aded2b90aaec33f54ee9a94be087929c432e1a
facility.clientId=187069
facility.email=singair-shr@gmail.com
facility.password=Sin@air321