#mci.referenceUrl=http://mci.mcishr.dghs.gov.bd
#mci.patientContext=/api/v1/patients
#mci.catchmentPathPattern=/api/v1/catchments/%s/patients
#mci.maxFailedEventCount=100

mci.referenceUrl=http://mci.mcishr.dghs.gov.bd
mci.patientContext=/api/v1/patients
mci.maxFailedEventCount=1000
mci.catchmentPathPattern=/api/default/catchments/%s/patients