shr.version=None
shr.referenceUrl=http://localhost:9997
shr.catchmentPathPattern=/catchments/%s/encounters
shr.patientEncPathPattern=/patients/%s/encounters
shr.maxFailedEventCount=1000

#shr.version=None
#shr.referenceUrl=http://shr.mcishr.dghs.gov.bd
#shr.catchmentPathPattern=/catchments/%s/encounters
#shr.patientEncPathPattern=/patients/%s/encounters
#shr.maxFailedEventCount=1000